### ISSUE TITLE
Redminer use XML

### ISSUE THREAD

**Issue by waghanza** [jeremy-w/redminer#1]
Hello,

I'm new redminer user (I love command line & I use redmine).

Currently, I'm just trying to install the tool.

``` sh
#> gem install redminer 
```

After configuring my new tool

``` sh
$> redmine install http://redmine.XXX.net
```

I can see that redmine try to access

``` ruby
/issues.xml
```

PS : on official redmine **redmine.org** I have a 

``` sh
/usr/share/gems/gems/activeresource-3.0.11/lib/active_resource/connection.rb:125:in `handle_response': Failed.  Response code = 301.  Response message = Moved Permanently. => http://www.redmine.org/issues.xml (ActiveResource::Redirection)
    from /usr/share/gems/gems/activeresource-3.0.11/lib/active_resource/connection.rb:114:in `request'
    from /usr/share/gems/gems/activeresource-3.0.11/lib/active_resource/connection.rb:79:in `block in get'
    from /usr/share/gems/gems/activeresource-3.0.11/lib/active_resource/connection.rb:217:in `with_auth'
    from /usr/share/gems/gems/activeresource-3.0.11/lib/active_resource/connection.rb:79:in `get'
    from /usr/share/gems/gems/activeresource-3.0.11/lib/active_resource/base.rb:857:in `find_every'
    from /usr/share/gems/gems/activeresource-3.0.11/lib/active_resource/base.rb:777:in `find'
    from /usr/share/gems/gems/activeresource-3.0.11/lib/active_resource/base.rb:803:in `all'
    from /usr/local/share/gems/gems/redmine-cli-0.1.1/lib/redmine-cli/cli.rb:20:in `list'
    from /home/slide/.gem/ruby/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /home/slide/.gem/ruby/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /home/slide/.gem/ruby/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /home/slide/.gem/ruby/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /usr/local/share/gems/gems/redmine-cli-0.1.1/bin/redmine:9:in `<top (required)>'
    from /usr/local/bin/redmine:23:in `load'
    from /usr/local/bin/redmine:23:in `<main>'
```

**redminer** try to parse XML, not json ?

**Comment by jeremy-w** [comment]
Looks like it's failing to follow a redirect based on `Response code = 301.  Response message = Moved Permanently.` If you can cadge ActiveResource into following redirects, it might work fine. It was pretty hacky to begin with, though.
